'use client';

import React from 'react';
import { Info, ShieldAlert, AlertTriangle, Database } from 'lucide-react';

export function MethodologyPanel() {
  return (
    <div className="bg-slate-900 border border-slate-800 rounded-xl overflow-hidden p-6 mt-8">
      <h3 className="text-sm font-semibold tracking-wide text-slate-300 uppercase mb-4 flex items-center gap-2">
        <Info className="w-4 h-4" />
        Intelligence Methodology & Limitations
      </h3>
      
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 text-sm text-slate-400 leading-relaxed">
        <div className="space-y-4">
          <div>
            <h4 className="text-slate-200 font-medium flex items-center gap-2 mb-2">
              <Database className="w-4 h-4 text-blue-400" />
              Rule-Based Explanations
            </h4>
            <p>
              The Environmental Intelligence layer translates simulated numerical data into structured, deterministic explanations. It aggregates signals, identifies trends, and compares current readings against configured prototype references to generate insights.
            </p>
          </div>
          <div>
            <h4 className="text-slate-200 font-medium flex items-center gap-2 mb-2">
              <AlertTriangle className="w-4 h-4 text-orange-400" />
              No Causal Inference
            </h4>
            <p>
              This prototype does not perform causal inference or attribute changes to specific real-world sources (e.g., factories, weather events). Explanations are strictly bounded to describing observed variations in the simulated data.
            </p>
          </div>
        </div>

        <div className="space-y-4">
          <div className="bg-orange-950/20 border border-orange-900/50 rounded-lg p-4">
            <h4 className="text-orange-400 font-medium flex items-center gap-2 mb-2">
              <ShieldAlert className="w-4 h-4" />
              Simulation Notice
            </h4>
            <ul className="list-disc pl-4 space-y-2 text-slate-300">
              <li>All sensor data presented in this view is <strong className="text-orange-300">simulated</strong> for demonstration purposes.</li>
              <li>Forecasts are generated by a prototype predictive engine, not an authoritative hydrological model.</li>
              <li>Priority scores and recommendations are part of a demonstration workflow and should not be treated as real-world operational directives.</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}
