"use client";
import React, { useMemo } from 'react';
import { useJalPulseStore } from '../../store/useJalPulseStore';
import { useSimulation } from '../../hooks/useSimulation';
import { getHistoryForRange, calculateHistoricalStats } from '../../lib/utils/analytics';
import { PARAMETER_METADATA } from '../../config/parameters';
import { formatValue } from '../../lib/utils/formatters';

export function StationComparisonTable() {
  const selectedParameter = useJalPulseStore(state => state.selectedParameter);
  const analyticsTimeRange = useJalPulseStore(state => state.analyticsTimeRange);
  const { history, snapshot } = useSimulation();

  const meta = selectedParameter ? PARAMETER_METADATA[selectedParameter] : null;

  const tableData = useMemo(() => {
    if (!selectedParameter) return [];
    
    return Object.keys(history).map(stId => {
      const rawData = getHistoryForRange(history, stId, selectedParameter, analyticsTimeRange);
      const stats = calculateHistoricalStats(rawData);
      const current = snapshot.stations[stId]?.readings[selectedParameter];
      
      return {
        id: stId,
        name: snapshot.stations[stId]?.name || stId,
        min: stats.min,
        max: stats.max,
        avg: stats.avg,
        current: current?.value || 0,
        status: current?.status || 'NORMAL'
      };
    });
  }, [history, snapshot, selectedParameter, analyticsTimeRange]);

  if (!meta || !tableData.length) return null;

  return (
    <div className="w-full px-4 md:px-8 py-8">
      <h3 className="text-sm font-bold tracking-[0.2em] text-accent mb-4 uppercase">Station Comparison ({analyticsTimeRange})</h3>
      
      <div className="w-full overflow-x-auto rounded-xl border border-border/50 bg-surface custom-scrollbar">
        <table className="w-full text-left border-collapse">
          <thead>
            <tr className="border-b border-border/50 bg-surface-elevated text-xs uppercase tracking-wider text-text-muted">
              <th className="p-4 font-semibold">Station</th>
              <th className="p-4 font-semibold text-right">Minimum</th>
              <th className="p-4 font-semibold text-right">Average</th>
              <th className="p-4 font-semibold text-right">Maximum</th>
              <th className="p-4 font-semibold text-right border-l border-border/50">Current</th>
            </tr>
          </thead>
          <tbody className="text-sm divide-y divide-border/30">
            {tableData.map(row => (
              <tr key={row.id} className="hover:bg-surface-elevated transition-colors">
                <td className="p-4">
                  <div className="font-semibold text-text-primary">{row.name}</div>
                  <div className="text-xs text-text-muted font-mono">{row.id}</div>
                </td>
                <td className="p-4 text-right font-mono text-text-secondary">{formatValue(row.min, meta.decimals)}</td>
                <td className="p-4 text-right font-mono font-bold text-accent">{formatValue(row.avg, meta.decimals)}</td>
                <td className="p-4 text-right font-mono text-text-secondary">{formatValue(row.max, meta.decimals)}</td>
                <td className={`p-4 text-right font-mono font-bold border-l border-border/50 ${row.status === 'CRITICAL' ? 'text-red-500' : row.status === 'WARNING' ? 'text-amber-500' : 'text-text-primary'}`}>
                  {formatValue(row.current, meta.decimals)}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <p className="mt-4 text-xs text-text-muted italic">Data shown in this prototype is generated by the Jal Pulse simulation engine. It is intended for interface and workflow demonstration.</p>
    </div>
  );
}
